INSERT INTO products (name, price, description, stock, color, genere, size, category_id, url_Img)
VALUES
	('Balon de futbol', 25.50, 'Balon de la final de la champions 2022', 30, 'AZUL', null, null, 3, 'https://i.postimg.cc/x1yX7hvM/ACCESORIO-BALONFUTBOL.jpg'),
	('Bolso Deportivo', 10.00, 'Bolso deportivo para viajar', 40, 'AZUL', 'Unisex', null, 3, 'https://i.postimg.cc/t7GgvN7B/ACCESORIO-BOLSADEPORTIVA.webp'),
	('Cama para saltar', 80.00, 'Cama para saltar con malla protectora', 20, 'VERDE', 'Unisex', null, 3, 'https://i.postimg.cc/DzvSK66D/ACCESORIO-CAMAPARASALTAR.jpg'),
	('Canasta de basket', 40.00, 'Canasta de basket con accesorios incluidos', 25, 'NARANJA', null, null, 3, 'https://i.postimg.cc/KjMz5HcK/ACCESORIO-CANASTADEBASKET.jpg'),
    ('Cuerda para saltar', 5.00, 'Cuerda para saltar con contador', 25, 'AZUL', null, null, 3, 'https://i.postimg.cc/mDqkCs4f/ACCESORIO-CUERDAPARASALTAR.webp'),
    ('Guante de beisbol', 15.00, 'Guante de beisbol con pelota de obsequio', 25, 'MARRON', null, null, 3, 'https://i.postimg.cc/ZYCwrt3f/ACCESORIO-GUANTEDEBEISBOLCONPELOTA.jpg'),
    ('Llaveros de futbol', 2.00, 'Llaveros de balon de la champions', 25, 'VERDE', null, null, 3, 'https://i.postimg.cc/MZNd5Pmz/ACCESORIO-LLAVEROBALON.webp'),
    ('Pack de boxeo', 120.00, 'Pack para practica de boxeo', 10, 'NEGRO', null, null, 3, 'https://i.postimg.cc/yNLk6RrN/ACCESORIO-PACKLUCHA.jpg'),
    ('Pesa', 20.00, 'Pesa con manija', 30, 'AZUL', null, null, 3, 'https://i.postimg.cc/SsjjnKwf/ACCESORIO-Pesoconmanijajpg.jpg'),
    ('Raqueta de tenis', 40.00, 'Raqueta de tenis marca wilson', 30, 'ROSA', null, null, 3, 'https://i.postimg.cc/RVtGD7gK/ACCESORIO-RAQUETADETENIS.jpg'),
    ('SmartWatch', 90.00, 'SmartWatch deportivo XIAOMI ', 30, 'NEGRO', null, null, 3, 'https://i.postimg.cc/0yqZRz43/ACCESORIO-SMARTWATCH.jpg'),
	('Buzo deportivo', 40.00, 'Buzo deportivo adidas color verde y naranja', 30, 'VERDE', 'HOMBRE', 'L', 1, 'https://i.postimg.cc/tgBzx2gQ/ROPA-BUZODEPORTIVOADIDAS-VERDE.webp'),
    ('Calentador', 40.00, 'Calentador adidas negro', 30, 'NEGRO', 'HOMBRE', '40', 1, 'https://i.postimg.cc/kgFsnn35/ROPA-CALENTADORADIDAS-HOMBRE-NEGRO.webp'),
	('Calentador ancho', 30.00, 'Calentador adidas ancho marron', 10, 'MARRON', 'MUJER', '36', 1, 'https://i.postimg.cc/5t43yZbS/ROPA-CALENTADORDISE-ODEVACA-CAFE-MUJER.webp'),
	('Camisa deportiva', 20.00, 'Camisa deportiva azul', 10, 'AZUL', 'UNISEX', '40', 1, 'https://i.postimg.cc/5t43yZbS/ROPA-CALENTADORDISE-ODEVACA-CAFE-MUJER.webp'),
    ('Camisa F.C BARCELONA', 100.00, 'Camisa F.C Barcelona Temporada 2019-2020', 10, 'AZUL', 'UNISEX', '40', 1, 'https://i.postimg.cc/50GqPyvs/ROPA-CAMISAFCBARCELONATEMP20192020-UNISEX.jpg'),
    ('Conjunto deportivo masculino', 100.00, 'Conjunto deportivo con calentador, buzo y camisa antitranspirante', 10, 'NEGRO', 'HOMBRE', '40', 1, 'https://i.postimg.cc/3NvjzhFY/ROPA-CONJUNTODEPORTIVO-HOMBRE.jpg'),
	('Conjunto deportivo femenino', 100.00, 'Conjunto deportivo con Crop-top y licra', 15, 'GRIS', 'MUJER', '36', 1, 'https://i.postimg.cc/BZLCj59k/ROPA-CONJUNTODEPORTIVO-MUJER-GRIS.jpg'),
    ('Conjunto deportivo femenino', 100.00, 'Conjunto deportivo con Crop-top y licra', 15, 'ROSA', 'MUJER', '36', 1, 'https://i.postimg.cc/ZYGxp9JR/ROPA-CONJUNTODEPORTIVO-MUJER-ROSA.webp'),
    ('Conjunto deportivo femenino', 80.00, 'Conjunto deportivo con Crop-top y Short', 17, 'AZUL', 'MUJER', '36', 1, 'https://i.postimg.cc/vH5LzQmv/ROPA-conjunto-Mujer-Azul.jpg'),
    ('Conjunto deportivo femenino', 80.00, 'Conjunto deportivo con Crop-top y licra', 17, 'NEGRO', 'MUJER', '36', 1, 'https://i.postimg.cc/Pq5WTYQ6/ROPA-CONJUTOPARAENTRENAR-MUJER-NEGRO.jpg'),
	('Vestido deportivo', 80.00, 'Vestido deportivo tenis', 17, 'NEGRO', 'MUJER', 'M', 1, 'https://i.postimg.cc/13P07Ln1/ROPA-VESTIDOTENIS-AZUL.jpg'),
    ('Zapatos adidas', 120.00, 'Zapatos adidas ultimate', 40, 'GRIS', 'MUJER', '35', 2, 'https://i.postimg.cc/CxNG3mkB/ZAPATOS-BLANCOSADIDAS-MUJER.jpg'),
    ('Zapatos Rebook', 150.00, 'Zapatos Rebook Fly', 37, 'NEGRO', 'MUJER', '35', 2, 'https://i.postimg.cc/G2BvsRNG/ZAPATOS-GRIS-UNISEX.webp'),
    ('Zapatos Adidas', 130.00, 'Zapatos con plataforma adidas clank', 42, 'GRIS', 'MUJER', '36', 2, 'https://i.postimg.cc/rsxWQJqp/ZAPATOS-PLATAFORMAS-BLANCOS-MUJER.jpg'),
    ('Zapatos Puma', 130.00, 'Zapatos Puma SCSW', 36, 'ROSA', 'MUJER', '36', 2, 'https://i.postimg.cc/y6ZF1V0z/ZAPATOS-ROSA-MUJER.webp'),
    ('Zapatos Nike', 110.00, 'Zapatos Nike SSSW', 36, 'NEGRO', 'MUJER', '36', 2, 'https://i.postimg.cc/rpZSmshq/ZAPATOS-DAISYNEGRO-MUJER.webp'),
	('Zapatos Coral', 110.00, 'Zapatos Coral SWwW', 15, 'NEGRO', 'MUJER', '42', 2, 'https://i.postimg.cc/qR9ysYVY/ZAPATOS-negros-Hombres.webp'),
    ('Bolso Spiderman', 15.00, 'Bolso deportivo spiderman negro', 23, 'NEGRO', 'UNISEX', null, 3, 'https://i.postimg.cc/ZnYqGxSH/ACCESORIO-BOLSODEPORTIVOSPIDERMAN.webp'),
    ('GORRA', 15.00, 'Gorra deportiva negra', 23, 'NEGRO', 'UNISEX', null, 3, 'https://i.postimg.cc/ZnYqGxSH/ACCESORIO-BOLSODEPORTIVOSPIDERMAN.webp'),
	('Aquatik Obsidian', 33.65, 'Traje de baño mujer', 17, 'AZUL', 'MUJER', 'M', 1, 'https://i.postimg.cc/kX44wswX/ROPA-AQUATIKOBSIDIAN.jpg'),
	('Jordan Drift', 44.65, 'Chaqueta deportiva para hombres', 17, 'GRIS', 'HOMBRE', 'L', 1, 'https://i.postimg.cc/mkdrB1Zs/ROPA-JORDANDRIFITSPORT.jpg'),
    ('Nike Air Fast', 13.65, 'Licra/Leggins para damas', 30, 'ROJO', 'MUJER', 'S', 1, 'https://i.postimg.cc/fRSbQb6G/ROPA-NIKEAIRFAST.jpg'),
    ('Camisa FC Barcelona Visitante', 40.65, 'Camisa FC Barcelona Visitante 2023-2024', 25, 'BLANCO', 'HOMBRE', 'L', 1, 'https://i.postimg.cc/Y2801Z6s/ROPA-NIKECAMISETABARCELONAVISTIA202324.jpg'),
    ('Nike Dry Fut Unlimited', 30.65, 'Short deportivo para hombre', 25, 'NEGRO', 'HOMBRE', 'L', 1, 'https://i.postimg.cc/VNjL5Vs4/ROPA-NIKEDRIFITUNLIMITED.jpg'),
	('Nike DryGraphic', 30.65, 'Buzo celeste deportivo para hombre', 25, 'AZUL', 'HOMBRE', 'L', 1, 'https://i.postimg.cc/WbH4yZfm/ROPA-NIKEDRYGRAPHIC.jpg'),
	('Nike Sport Wear Air', 15.65, 'Conjuto negro para mujer', 25, 'NEGRO', 'MUJER', 'S', 1, 'https://i.postimg.cc/QMLd83DH/ROPA-NIKESPORTWEARAIR.jpg'),
    ('3ra Equipacion River Plate', 26.65, 'Camisa Visitante River Plate 2023', 30, 'NEGRO', 'HOMBRE', 'L', 1, 'https://i.postimg.cc/KYymXD7T/ROPA-RIVER.jpg'),
	('Under Armour Qualifier', 26.65, 'Camisa antitranspirante para mujer', 30, 'ROSA', 'MUJER', 'L', 1, 'https://i.postimg.cc/XqvVHNfD/ROPA-UNDERARMOURQUALIFIER.jpg'),
    ('Adidas Barricade', 48.65, 'Zapatos adidas para correr', 10, 'BLANCO', 'UNISEX', '35', 2, 'https://i.postimg.cc/kGh7krwM/ZAPATOS-ADIDASBARRICADE.jpg'),
	('Adidas Predator Accuracy.1 césped natural seco', 333.65, 'Zapatos Fútbol Hombre/Mujer', 10, 'NARANJA', 'UNISEX', '35', 2, 'https://i.postimg.cc/pV0V98xN/ZAPATOS-ADIDASPREDATORACCURACY.jpg'),
    ('Adidas Terrex free Hiker', 262.65, 'Zapatos Aventura Mujer', 10, 'GRIS', 'MUJER', '32', 2, 'https://i.postimg.cc/rFKV5mFD/ZAPATOS-ADIDASTERREXFREEHIKER.jpg'),
	('Adidas Ultra Boost Ligth', 210.65, 'Zapatos Correr Hombre/Mujer', 10, 'BLANCO', 'UNISEX', '32', 2, 'https://i.postimg.cc/BQkqp0XM/ZAPATOS-ADIDASULTRABOOSTLIGHT.jpg'),
    ('Air Jordan 1', 210.65, 'Zapatos Básquet Hombre', 10, 'AMARILLO', 'HOMBRE', '32', 2, 'https://i.postimg.cc/8zvTn0vD/ZAPATOS-AIRJORDAN1.jpg'),
    ('Vasari negros LO', 65.65, 'Zapatos vasari unisex', 10, 'NEGRO', 'UNISEX', '32', 2, 'https://i.postimg.cc/5tqbfQpR/ZAPATOS-NEGROSVASARI.webp'),
    ('Nike AirForce 1', 300.45, 'Zapatos deportivos hombre', 15, 'GRIS', 'HOMBRE', '40', 2, 'https://i.postimg.cc/XJj3qNz7/ZAPATOS-NIKEAIRFORCE1.jpg'),
	('Nike Zoom Super', 120.45, 'Zapatos deportivos hombre', 15, 'GRIS', 'HOMBRE', '40', 2, 'https://i.postimg.cc/nz3xD8yK/ZAPATOS-NIKEZOOMSUPERREP.jpg'),
    ('Vasari Taupe', 19.45, 'Zapatos deportivos unisex', 10, 'GRIS', 'UNISEX', '40', 2, 'https://i.postimg.cc/MKMwvFdR/ZAPATOS-TAUPEVASARI.webp'),
	('Under Armour', 40.45, 'Zapatos deportivos casuales', 15, 'BLANCO', 'UNISEX', '40', 2, 'https://i.postimg.cc/ryYcykCM/ZAPATOS-UNDERARMOUR.jpg');
    
    
    

